project_id = "xqgtwzpmuxkeqpykrxmd"

[functions.send-employee-invitation]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.check-user-exists]
verify_jwt = true
