// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqgtwzpmuxkeqpykrxmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxZ3R3enBtdXhrZXFweWtyeG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzgwMzAsImV4cCI6MjA2OTgxNDAzMH0.5Wxgnt6U2xwi9s2YZfxn3G4hQPsREOgiH2XrqRYDd0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});